server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: santacruz-venta-service
          uri: lb://santacruz-venta-service
          predicates:
            - Path=/ventas/**
            - Path=/mediodepagos/**
            - Path=/ventadetalles/**
          filters:
            - AuthFilter

        - id: santacruz-compra-service
          uri: lb://santacruz-compra-service
          predicates:
            - Path=/compras/**
            - Path=/compradetalles/**
          filters:
            - AuthFilter

        - id: santacruz-almacen-service
          uri: lb://santacruz-almacen-service
          predicates:
            - Path=/productos/**
            - Path=/categorias/**
          filters:
            - AuthFilter

        - id: santacruz-empresa-service
          uri: lb://santacruz-empresa-service
          predicates:
            - Path=/sucursales/**
            - Path=/empresas/**
          filters:
            - AuthFilter

        - id: santacruz-usuario-service
          uri: lb://santacruz-usuario-service
          predicates:
            - Path=/trabajadores/**
            - Path=/clientes/**
          filters:
            - AuthFilter

        - id: santacruz-auth-service
          uri: lb://santacruz-auth-service
          predicates:
            - Path=/auth/**
